logging:
  level:
    root: debug
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/,classpath:config/license-service,file://F:/springboot/config-server/src/main/resources/config/license-service
          searchPaths: license-service
server:
  port: 8071
